// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmLpvFcUFR4UxnlMs3mAI-eJ1n9-e83s',
    appId: '1:498753005046:web:e494bed134f18a6e7113d7',
    messagingSenderId: '498753005046',
    projectId: 'shine-9eaa6',
    authDomain: 'shine-9eaa6.firebaseapp.com',
    storageBucket: 'shine-9eaa6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9DCXxfusyEpWSKOwkrdkIaYVa5dH2OiY',
    appId: '1:498753005046:android:bf0ad729b773089e7113d7',
    messagingSenderId: '498753005046',
    projectId: 'shine-9eaa6',
    storageBucket: 'shine-9eaa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQuq4Q0ZgqZR6CsSh2RbqQSRFMsGHMaI',
    appId: '1:498753005046:ios:2ed1831cd1468c4a7113d7',
    messagingSenderId: '498753005046',
    projectId: 'shine-9eaa6',
    storageBucket: 'shine-9eaa6.appspot.com',
    iosBundleId: 'com.example.shine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQuq4Q0ZgqZR6CsSh2RbqQSRFMsGHMaI',
    appId: '1:498753005046:ios:87f55812fd050c5e7113d7',
    messagingSenderId: '498753005046',
    projectId: 'shine-9eaa6',
    storageBucket: 'shine-9eaa6.appspot.com',
    iosBundleId: 'com.example.shine.RunnerTests',
  );
}
